sudo: true

language: java

services:
  - docker

cache:
  directories:
  - "$HOME/.cache"

before_install:
  - "cp .travis.settings.xml $HOME/.m2/settings.xml"

install:
  - "mvn fabric8:install"
  - "export PATH=$HOME/.fabric8/bin:$PATH"

deploy:
  provider: script
  script: "Y | mvn clean install -p docker-build-image,docker-push-image"
  skip_cleanup: true
  on:
    tags: true

env:
  global:
  - secure: JekTAuMFRm8BlNIvYo3Y67fUkoURUlzTuDLazTSU/6qwhI7McKTfKdAtwi5p23CKfI5hlRBMYPD/WM74uZsNBGNGsfEdDKCtOq04l3vs/BFPY8To8lHrOv7aPHJJzYddg0nJtSRfZKLaZB3/ZJUHBQ7Y0Vkt/jCyzf46qirnKjCBM8SvoCSTRpF2Pj8JQihkSM3anv0pYvCsVueSVDkX8hXXKen8VlLl23joxxGpHyv42lRLIdV78Pc/p7i/7WjRZzZr/gcF23XRjWU8/TKoresB5TrIdpUcVZZ1Fnzh1bTVNwbIWLcl9vNc0UeDCnwzX+tAjmyUkfAsKtpA7UU0JxEGJw5WeOxXA/voYetktKiBGgLS0cUDKi2Z3jLC12OOB6M9eQDh7ZHnjn9A6W/aWh4pwFiNM7x/x8KX7DRXpYtS5dR31pqNPQrLY23D4WWUnikX+Sw3CEhA15LHWPVyMnSHfGzJnB68uRaqyzSJhbQDOH8XYBj/7IKgUT/ukKM/fPtoprhc/jkLdayI+ZE5MJM/6yeufE9OGJi+cc6LgPQfd+1zxoqOAUsgeuy35aQAZUpKUjg+L7JmCkZ8acRb081dR3OO9CNidT23ffLKpJiSN4sA5g5wV/AHsCSPjzGemq22FvLeyhkgdr7/TiD+jwEXTDm8Uw6YX8FXdSUtBRY=
  - secure: nuKPts9+QiPgUbcHkpQ/PTcv24v7uPs1Sys72HNNjtNK0Zm44zFbb47MXL9cGC4o0fr3edr5J+RQft6i5q1OasdhnSHOLNYGNpDqIN2Y/boT4rMnOVVFCSBnkk+q0J+aKUu7uQYuWcAOvzPyDmvp6+0xpjELVJPRXLOrFalgZN8hiRfFYie/1P6jAcAzKjN3VejuVwafTFUnwVvd61glWYXt/cqN5Pbr3kwklnyqyeuliZFxVmFMDvSSg+4EseG6D8BA5SjLONBqEQNEP0edH0ZbpB95wHhMn5mspCZXImAdfC4hxTgM0oCisllbBHuMBi26N/xFzAetptNdrt/z7XvecXvtYlXnvnmT2rPjWZMb4atd8/uVScpMwwqm2lKKFk/E2SuqRRFxcIdUo2LKtLko5fouhvWffRUPQUPH/oGv6dDVoY1ywTgLr6DWiJKtv3nbRgiW/QUPZJ27ztEovGWqsdwl2n3dGzMXU/C0sj6cBpmvuZ9I29qrCyoM4a0+fzi+rrUpAdorhWTd1CNAf2hp+lYOeqNQYTB8ffjVqooTVl1rufbaKqphUFWk3GXOZF3gJLZLMhQcyCBO42HWzNfbokbAIHjP2qESIcIuXijg8AzWyDRs1vvZnOlRQMYzNQZGv9GZwPuv+/mYLdDObjPRyLWt0HUtk7vX0U72UFU=
